In [5]:
import numpy as np #alias create of numpy



In [2]:
arr = np.array([25,41,63,89,78,]) #list pass in array
arr

array([25, 41, 63, 89, 78])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
lst = ([25,41,63,89,78,]) #create array
arr = np.array(lst)
arr

array([25, 41, 63, 89, 78])

In [6]:
lst = ([25,41,63,89,78, 'hello']) #homogeneous data
arr = np.array(lst)
arr

array(['25', '41', '63', '89', '78', 'hello'], dtype='<U11')

In [7]:
#indexing in numpy array
arr[2] #accsess item from list

'63'

In [8]:
arr[2:4]

array(['63', '89'], dtype='<U11')

In [9]:
arr[2:]

array(['63', '89', '78', 'hello'], dtype='<U11')

In [10]:
arr[:]

array(['25', '41', '63', '89', '78', 'hello'], dtype='<U11')

In [11]:
arr[::]

array(['25', '41', '63', '89', '78', 'hello'], dtype='<U11')

In [12]:
arr[::1] #bydefault 1

array(['25', '41', '63', '89', '78', 'hello'], dtype='<U11')

In [13]:
arr[::-1]

array(['hello', '78', '89', '63', '41', '25'], dtype='<U11')

In [14]:
arr[-1:-3:-1]  #accsess item from right

array(['hello', '78'], dtype='<U11')

In [15]:
arr[-1:-3]

array([], dtype='<U11')

In [16]:
arr.ndim  #no.of dimention

1

In [18]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
np.zeros(10)  #dummy array 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
### 1 - 10
np.linspace(1,5,10)  #betwwen 1 to 5  with 10 item

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
arr2 = np.array([[52,63,52,85],
                 [42,63,52,85],
                 [52,63,52,85]])

In [24]:
arr.shape()

TypeError: 'tuple' object is not callable

In [26]:
arr2[2]

array([52, 63, 52, 85])

In [27]:
arr2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [28]:
arr2[0:2]

array([[52, 63, 52, 85],
       [42, 63, 52, 85]])

In [29]:
#[row,column] #starting_point:ending_point:step_point
arr2[1:3]  #access row

array([[42, 63, 52, 85],
       [52, 63, 52, 85]])

In [30]:
arr2[1:3,2:] #access row & column

array([[52, 85],
       [52, 85]])

In [32]:
arr2[-1,-1]

85

In [33]:
arr2[2,3]

85

In [35]:
arr2[2][3]

85

In [36]:
arr3 = np.arange(60)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [37]:
#transformation 1d to 2d array
arr3 = np.arange(60).reshape(12,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [38]:
#trasform 2d to 1d
arr3.ravel()    #ravel(),flatten(),reshape()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
arr3.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [40]:
np.random.random(10)   #create randommly array

array([0.7805696 , 0.17927799, 0.33576057, 0.68424021, 0.92582604,
       0.52719196, 0.18820731, 0.36346997, 0.27369523, 0.86880083])

In [41]:
np.random.random((10,2))

array([[0.2277901 , 0.73149414],
       [0.50939307, 0.84090063],
       [0.60588274, 0.88828087],
       [0.04038681, 0.65284214],
       [0.75580816, 0.29628599],
       [0.57503253, 0.22553109],
       [0.66620387, 0.41557023],
       [0.95261781, 0.33692157],
       [0.7610413 , 0.21706877],
       [0.03405005, 0.23198616]])

In [42]:
np.random.randint(1,5,10)

array([1, 1, 2, 4, 1, 4, 4, 3, 3, 1])

In [43]:
#to replace value
arr[-1]

'hello'

In [49]:
arr[-1]

100

In [48]:
arr[-1] = 100  #to replace value in a array at -1 pr 
arr

array([ 88,  69,  31, 190,  23,  98, 116, 190,  56,  63,  81, 193, 173,
       121,  88, 131,  33, 103,  18, 159, 127, 170, 101,  32,  11,  54,
       159,  99, 101, 105, 194,  91, 154, 172,  42,   1, 116, 172, 118,
       173, 121, 105,  73,  83, 117,  72, 159, 155,  25,  80,  26,  20,
        69, 115, 196, 121, 170, 195, 121,  46, 185, 184,  79, 164, 151,
        17,  50,  91,  55,  47, 110,  61, 150, 125, 185,  28, 123, 119,
       190,  50, 124,  52, 177, 108, 108, 124,  83, 165,  10, 159, 198,
        33,  72,  63,  42,  90, 106, 118,  94,   1, 140,  73, 115, 143,
       129, 135,  56,  40, 135,  17, 190,  51, 129, 195, 186, 144,  24,
       181, 102,   5, 109,  15, 163,  56,  68,  95,  73,   4,  97, 108,
        87, 117,  19,  42,  58,  96, 154, 140,  84,  23,  90,  52,   9,
       198,  13, 102, 173, 146, 167, 191,  43,   6,  45,  81,   9, 199,
        18, 142,  57, 189, 159,   8, 152, 148,  58,  20,  51,  28, 122,
        90,  47,  81, 105,  19,   2, 122, 143,  35, 123,  55, 13

In [47]:
arr = np.random.randint(1,200,200)
arr

array([ 88,  69,  31, 190,  23,  98, 116, 190,  56,  63,  81, 193, 173,
       121,  88, 131,  33, 103,  18, 159, 127, 170, 101,  32,  11,  54,
       159,  99, 101, 105, 194,  91, 154, 172,  42,   1, 116, 172, 118,
       173, 121, 105,  73,  83, 117,  72, 159, 155,  25,  80,  26,  20,
        69, 115, 196, 121, 170, 195, 121,  46, 185, 184,  79, 164, 151,
        17,  50,  91,  55,  47, 110,  61, 150, 125, 185,  28, 123, 119,
       190,  50, 124,  52, 177, 108, 108, 124,  83, 165,  10, 159, 198,
        33,  72,  63,  42,  90, 106, 118,  94,   1, 140,  73, 115, 143,
       129, 135,  56,  40, 135,  17, 190,  51, 129, 195, 186, 144,  24,
       181, 102,   5, 109,  15, 163,  56,  68,  95,  73,   4,  97, 108,
        87, 117,  19,  42,  58,  96, 154, 140,  84,  23,  90,  52,   9,
       198,  13, 102, 173, 146, 167, 191,  43,   6,  45,  81,   9, 199,
        18, 142,  57, 189, 159,   8, 152, 148,  58,  20,  51,  28, 122,
        90,  47,  81, 105,  19,   2, 122, 143,  35, 123,  55, 13

In [50]:
arr <100 

array([ True,  True,  True, False,  True,  True, False, False,  True,
        True,  True, False, False, False,  True, False,  True, False,
        True, False, False, False, False,  True,  True,  True, False,
        True, False, False, False,  True, False, False,  True,  True,
       False, False, False, False, False, False,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False, False,  True, False, False,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False, False, False,  True, False, False, False,  True, False,
        True, False, False, False, False,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True, False,  True, False, False, False, False,  True,  True,
       False,  True, False,  True, False, False, False, False,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
        True,  True,

In [51]:
arr[arr<100]   #print item less then 100

array([88, 69, 31, 23, 98, 56, 63, 81, 88, 33, 18, 32, 11, 54, 99, 91, 42,
        1, 73, 83, 72, 25, 80, 26, 20, 69, 46, 79, 17, 50, 91, 55, 47, 61,
       28, 50, 52, 83, 10, 33, 72, 63, 42, 90, 94,  1, 73, 56, 40, 17, 51,
       24,  5, 15, 56, 68, 95, 73,  4, 97, 87, 19, 42, 58, 96, 84, 23, 90,
       52,  9, 13, 43,  6, 45, 81,  9, 18, 57,  8, 58, 20, 51, 28, 90, 47,
       81, 19,  2, 35, 55, 84, 10, 65, 27, 89, 11, 52, 30,  6])

In [52]:
arr[arr<100].shape

(99,)

In [6]:
[[[1,2,3],    #3d array
 [4,5,6]],
[[1,2,3],
 [4,5,6]],
[[1,2,3],
 [4,5,6]],
[[1,2,3],
 [4,5,6]]]

arr = np.array([[[1,2,3],
 [4,5,6]],
[[1,2,3],
 [4,5,6]],
[[1,2,3],
 [4,5,6]],
[[1,2,3],
 [4,5,6]]])

arr


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
arr.ndim

3

In [10]:
arr.shape  #[table ,row,column]

(4, 2, 3)

In [9]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

arr[1:0:]   #slicing(element fatch) 

In [12]:
arr[1, 0, : ]

array([1, 2, 3])

In [13]:
arr[1, 0, 2]

3

In [14]:
arr[1, 0, :][2]

3

In [16]:
a = arr[1, 0, :]

In [17]:
a[::-1]

array([3, 2, 1])

In [18]:
arr[2,1,1:]   #1: start from 1 to all column

array([5, 6])

In [19]:
arr[2][1][1:]

array([5, 6])

In [20]:
arr[0][0][0:3]

array([1, 2, 3])

In [21]:
arr[0:2][0:2][0:3]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
arr[:,0,:]  #: from all tables

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
arr[:,1,:]

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [28]:
arr1 = np.random.random((3,2))
arr1

array([[0.91368022, 0.99824478],
       [0.50434779, 0.38848579],
       [0.12670912, 0.86749449]])

In [25]:
arrr2.shape

NameError: name 'arrr2' is not defined

In [26]:
arr2.shape

(3, 2)

In [27]:
arr2.T  #transpose

array([[0.49641986, 0.75409579, 0.53296691],
       [0.80494446, 0.68049223, 0.04641659]])

In [29]:
arr2 = np.random.random((3,2))
arr2

array([[0.76376557, 0.90024596],
       [0.99200488, 0.72338226],
       [0.07350596, 0.65825914]])

In [30]:
arr1.shape

(3, 2)

In [31]:
arr2.T

array([[0.76376557, 0.99200488, 0.07350596],
       [0.90024596, 0.72338226, 0.65825914]])

In [32]:
arr1.shape

(3, 2)

In [33]:
arr2.shape

(3, 2)

In [34]:
np.concatenate((arr1,arr2),axis=0)  #axis=0 bydefault axis =0 vertically

array([[0.91368022, 0.99824478],
       [0.50434779, 0.38848579],
       [0.12670912, 0.86749449],
       [0.76376557, 0.90024596],
       [0.99200488, 0.72338226],
       [0.07350596, 0.65825914]])

In [37]:
np.concatenate((arr1,arr2),axis=1)

array([[0.91368022, 0.99824478, 0.76376557, 0.90024596],
       [0.50434779, 0.38848579, 0.99200488, 0.72338226],
       [0.12670912, 0.86749449, 0.07350596, 0.65825914]])

In [39]:
np.concatenate((arr1,arr2))

array([[0.91368022, 0.99824478],
       [0.50434779, 0.38848579],
       [0.12670912, 0.86749449],
       [0.76376557, 0.90024596],
       [0.99200488, 0.72338226],
       [0.07350596, 0.65825914]])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#matrix operation

arr + 5   #5 increment in each array elements

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
arr.min()

0

In [44]:
arr.mean() #min, max, sum

4.5

In [45]:
arr.max()

9

In [47]:
#multiplication of 2d  & 1d array

arr1 = np.array([[1,2,3],[4,5,6]])

arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr = np.array([2,2,2])
arr

array([2, 2, 2])

In [49]:
arr1 + arr #add 2d & 1d array

array([[3, 4, 5],
       [6, 7, 8]])

In [50]:
arr1 * arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
arr2 = np.array([[1,1,1],[2,2,2]])
arr2

array([[1, 1, 1],
       [2, 2, 2]])

In [53]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr1 + arr2

array([[2, 3, 4],
       [6, 7, 8]])

In [55]:
arr = np.array([4,6,7,1,8])
arr

array([4, 6, 7, 1, 8])

In [56]:
arr.sort() #sorting array

In [57]:
arr

array([1, 4, 6, 7, 8])

In [59]:
arr.argsort()   #

array([0, 1, 2, 3, 4], dtype=int64)

In [60]:
arr.argmin()

0

In [61]:
arr.argmax()

4